###########################################################################
############################ Find haplotypes#### ##########################
###########################################################################

# By Pierre-Louis Stenger
# Upload 19.01.2017

############################ Data presentation ############################

# Data in file "Alignement.fas" are many DNA sequences like these:
# Les données dans le fichier "Alignement.fas" sont de nombreuses séquences d'ADN comme celles ci:

>ttr_05
CTTATTGTACAGTTACCACAACACCACAGTACTACGTCAGTATTAAAAGTAATTTGTTTT
AAAAACATTTTACTGTACACATTACATATACATACACATGCGCATGCTAATATTTAGTCT
CTCCTTGTAAATATTCATATATACATGCTATGTATTATTGTGCATTCATTTATTTTCCAT
ACGATAAGTTAAAGCCCGTATTAATTATCATTAATTTTACATATTACATAATATGTATGC
TCTTACATATTATATCTCCCCTATCAATTCTACCTCCATTATATCCTATGGTCACTCCAT
TAGATCACGAGCTTAATCACCATGCCGCGTGAAACCAGCAACCCGCTCGGCAGGGATCCC
TCTTCTCGCACCGGGCCCATATCTCGTGGGGGTAGCTAATAATGATCTTTATAAGACATC
TGGTTCTTACTTCAGGACCATTTTAACTTAAAATCGCCCACTCGTTCCCCTTAAATAAGA
CATCTCGATGGACTCATGACTAATCAGCCCATGCCTAACATAACTGAGGTTTCATACATT
TGGTATTTTTTAATTTTTGGGGGGGAGCTTGCACCGACTCAGCTATGGCCTTGGGAAGGC
CCCGTCACAGTCAAATAAATTGTAGCTGGACCTGTGTGTATTTTTGATTGGACTAGCACA
ACCAACAGGTGTTATTTAATTA
>ttr_07
CTTATTGTACAGTTACCACAACACCACAGTACTACGTCAGTATTAAAAGTAATTTGTTTT
AAAAACATTTTACTGTACACATTACATATACATACACATGCGCATGCTAATATTTAGTCT
CTCCTTGTAAATATTCATATATACATGCTATGTATTATTGTGCATTCATTTATTTTCCAT
ACGATAAGTTAAAGCCCGTATTAATTATCATTAATTTTACATATTACATAATATGTATGC
TCTTACATATTATATCTCCCCTATCAATTCTACCTCCATTATATCCTATGGTCACTCCAT
TAGATCACGAGCTTAATCACCATGCCGCGTGAAACCAGCAACCCGCTCGGCAGGGATCCC
TCTTCTCGCACCGGGCCCATATCTCGTGGGGGTAGCTAATAATGATCTTTATAAGACATC
TGGTTCTTACTTCAGGACCATTTTAACTTAAAATCGCCCACTCGTTCCCCTTAAATAAGA
CATCTCGATGGACTCATGACTAATCAGCCCATGCCTAACATAACTGAGGTTTCATACATT
TGGTATTTTTTAATTTTTGGGGGGGAGCTTGCACCGACTCAGCTATGGCCTTGGGAAGGC
CCCGTCACAGTCAAATAAATTGTAGCTGGACCTGTGTGTATTTTTGATTGGACTAGCACA
ACCAACAGGTGTTATTTAATTA


############################### R Script ################################


# Connaître le nombre d'haplotypes et quels individus en sont porteurs:
# To know the number of haplotypes and which individuals carry them:

library(pegas)
ttr = read.dna("Alignement.fas", format="fasta")
h <- haplotype(ttr, labels = NULL)
attr(h, "index")
